<?php

//Custom module developed to create CCE roles by subadmin. Also showing the power of drupal form API using hooks.

//This is the function to provide the URL for the form with additional arguments to set the user permissions. 
function editcce_menu() {
  $items['editcce'] = array(
    'page callback' => 'drupal_get_form',
	//'type' => MENU_CALLBACK,
    'page arguments' => array('editcce_form'),
	'access arguments' => array('access editcce content'),
    );
  return $items;
}

function editcce_form($form,&$form_state) {
	if(!isset($_REQUEST['uid']))
	{
	global $base_url;
	$url=$base_url."/pagenotfound";
	drupal_goto($url);
	}

global $base_url;	
$uid=$_REQUEST['uid'];
$existingUser = user_load($uid);
$uname=$existingUser->name;

//echo "<pre>"; print_r($existingUser);
//die();	
drupal_set_title($title = "SUB ADMIN Panel ##   Editing:".$uname, $output = CHECK_PLAIN);

 $form['#attributes'] = array('class' => 'cceform');
 //$form['#action'] = $base_url.'/saveccedetails';
 
  $form['empid'] = array(
    '#title' => t('Employee ID'),
    '#type' => 'textfield',
	'#default_value' => isset($existingUser->field_employee_id['und'])?$existingUser->field_employee_id['und'][0]['value']:null,
    '#required' => FALSE,
  );
  
  $form['empdept'] = array(
    '#title' => t('Employee Department'),
    '#type' => 'textfield',
	'#default_value' => isset($existingUser->field_employee_department['und'])?$existingUser->field_employee_department['und'][0]['value']:null,
    '#required' => FALSE,
  );
  
    $form['empextn'] = array(
    '#title' => t('Employee Extension Number'),
    '#type' => 'textfield',
	'#default_value' => isset($existingUser->field_employee_extension['und'])?$existingUser->field_employee_extension['und'][0]['value']:null,
    '#required' => FALSE,
  );
  

  
    $form['password'] = array(
    '#title' => t('Re-enter changed password'),
    '#type' => 'password_confirm',
    '#required' => FALSE,
  );
  
     $form['userid'] = array(
    '#type' => 'hidden',
    '#required' => TRUE,
	'#value' => $uid,
  );
  
  
  
//	$form['ccedetails'] = array(
//  '#type' =>'button', 
//  '#value' => t('See ALL CCE Details'), 
//  '#weight' => 19,
//  '#attributes' => array('onclick' => 'document.location.href="mycce"; return false;'),
//);

  	 //$form["#validate"][] = 'editcce_form_validate';
  //Submit will go to the submit function where a new CCE will be created
  $form['submit'] = array(
    '#value' => t('Save CCE Information'),
    '#type' => 'submit',
	'#executes_submit_callback' => TRUE,
    '#limit_validation_errors' => FALSE,
    );
	

	//$form['#submit']['#validate'][]='custom_validate';
  return $form;

}

function editcce_form_validate($form, &$form_state) {
global $base_url;	
  if (($form_state['input']['password']['pass1'] != $form_state['input']['password']['pass2'])){
  
    form_set_error('password', t('The two passwords should match..........'));

  }
  else
  {
  $url=http_build_query($form_state['values']);
  $url=$base_url."/saveccedetails?".$url;
  drupal_goto($url);
  }
}


function editcce_permission() {
  return array(
    'access editcce content' => array(
      'title' => t('Access content for the Admin Panel module'),
    )
  );
}





