<?php
/**
 * @file
 * This is the main module file.
 */

/**
 * Implements hook_help().
 */
function shownodes_help($path, $arg) {

  if ($path == 'admin/help#shownodes') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The shownodes module allows the Administrator to display various types of nodes as a block on your Drupal site.') . '</p>';
    return $output;
  }
}

/**
* Implementation of hook_menu().
*/
/*
function shownodes_menu() {

  $items['admin/config/shownodes'] = array(
  'title' => t('Choose the nodes to show'),
  'description' => t('You can select which node types you want to show'),
  'page callback' => 'system_admin_menu_block_page',
  'access arguments' => array('administer site configuration'),
  'file' => 'system.admin.inc',
  'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/shownodes/settings'] = array(
  'title' => t('Choose the nodes to show'),
  'description' => t('You can select which node types you want to show'),
  'page callback' => 'drupal_get_form',
  'page arguments' => array('shownodes_admin_settings'),
  'access arguments' => array('administer site configuration'),
  'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}*/

function getData($url, $params=array()) 
{   

            $url = $url.'?'.http_build_query($params, '', '&');
            
            $ch = curl_init();
            
            curl_setopt($ch, CURLOPT_URL, $url);
            
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            
            curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 10);

            curl_setopt($ch, CURLOPT_HTTPHEADER, array( 'Content-Type: application/json'));
            
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
                
            $response = curl_exec($ch);
            
            curl_close($ch);
            
            return $response;
}

function shownodes_menu() {
  $items = array();
  $items['shownodes'] = array( // change 'foo/myurl' to the url you want
    'title' => 'Callback',
    'type' => MENU_CALLBACK,
    'page callback' => 'custom_callback',
    'access arguments' => array('access content'),
  ); 
  return $items;
}

function custom_callback () {
  // Parse $_REQUEST parameters
 
  if(isset($_REQUEST['d']) && $_REQUEST['d'] != array())
  {
    $bodycontent = $_REQUEST['d'];
    $data = base64_decode($_REQUEST['d']);

    $data = explode("###", $data);

    parse_str($data[0], $noofpassengersandallflightdata);
    parse_str($data[1], $creditcarddata);
    parse_str($data[2], $customerinfo);
    $allflightdata = $noofpassengersandallflightdata['allflightdata'];
    $allflightdata = str_replace("'", '"', $allflightdata);

    $allflightdatatosave = $allflightdata;

    $allflightdata = json_decode($allflightdata);

    $bookingdata = $allflightdata;

    $bookingdatatocheck = $bookingdata;
      /*echo "<pre>"; 
          print_r($bookingdata);
          print_r($noofpassengersandallflightdata); 
          print_r($creditcarddata); 
          print_r($customerinfo); 

          die;*/
   
        $nameofmktairline = "";
        $flightarray = array();
        $flightarrayoutbound = array();

        if(isset($bookingdata->inoutflightarr) && $bookingdata->inoutflightarr)
        {
            //amadeus data
            $ikey = 0;
            foreach ( $bookingdata->inoutflightarr as $key => $value) {  //echo "<pre>"; print_r($value); die;
                $nameofmktairline = $value->marketingairlinefullname;
                

                $flightarray[$ikey]['logoofairline'] = $value->logoofmarketingairline;
                $flightarray[$ikey]['nameofairline'] = $value->marketingairlinefullname;
                $flightarray[$ikey]['depart'] = $value->departtime;
                $flightarray[$ikey]['originairport'] = $value->departureairportfullname;
                $flightarray[$ikey]['arrives'] = $value->arrivaltime;
                $flightarray[$ikey]['destinationairport'] = $value->arrivalairportfullname;
                $flightarray[$ikey]['flightno'] = $value->flightno;
                $flightarray[$ikey]['stops'] = $value->stopornonstop;
                $flightarray[$ikey]['fare'] = $bookingdata->totalfare;
                $flightarray[$ikey]['travelclass'] = $value->travelclass;
                $flightarray[$ikey]['layovertime'] = $value->layovertime;

                $totalprice = $bookingdata->totalfare;
                $priceperadulttotalfare = $bookingdata->totaltax;
                $priceperadulttax = $bookingdata->totalbeforetax;

                $ikey++;
            }

          
        }

        /*if(isset($bookingdata->datatoshownew) && $bookingdata->datatoshownew)
        {
            
            foreach ( $bookingdata->datatoshownew as $key => $value) 
            {   
                $nameofmktairline = $value->nameOfmarketingAirine; 
                $adult = $value->adults;
                $children = $value->children;
                if($key == 0)
                {    
                    

                    foreach ($value->AllFlightsdataInOneOption as $keynext => $valuenext) 
                    {
                        $flightarray[$keynext]['logoofairline'] = $value->logoOfmarketingAirine;
                        $flightarray[$keynext]['nameofairline'] = $value->nameOfmarketingAirine;
                        $flightarray[$keynext]['stops'] = $value->nonStopOrwithStop;
                        $flightarray[$keynext]['layovertime'] = $value->LayoverTime;
                        $flightarray[$keynext]['travelclass'] = $value->searchedClass;
                        $flightarray[$keynext]['fare'] = $bookingdata->totalfareInUsd;
                        $flightarray[$keynext]['depart'] = $valuenext->departuretime;
                        $flightarray[$keynext]['originairport'] = $valuenext->departureairport;
                        $flightarray[$keynext]['arrives'] = $valuenext->arrivaltime;
                        $flightarray[$keynext]['destinationairport'] = $valuenext->arrivalaiport;
                        $flightarray[$keynext]['flightno'] = $valuenext->oafn;
                    }
                }else
                { 
                    

                    foreach ($value->AllFlightsdataInOneOption as $keynext => $valuenext) {

                        $flightarrayoutbound[$keynext]['logoofairline'] = $value->logoOfmarketingAirine;
                        $flightarrayoutbound[$keynext]['nameofairline'] = $value->nameOfmarketingAirine;
                        $flightarrayoutbound[$keynext]['stops'] = $value->nonStopOrwithStop;
                        $flightarrayoutbound[$keynext]['layovertime'] = $value->LayoverTime;
                        $flightarrayoutbound[$keynext]['travelclass'] = $value->searchedClass;
                        $flightarrayoutbound[$keynext]['fare'] = $bookingdata->totalfareInUsd;
                        $flightarrayoutbound[$keynext]['depart'] = $valuenext->departuretime;
                        $flightarrayoutbound[$keynext]['originairport'] = $valuenext->departureairport;
                        $flightarrayoutbound[$keynext]['arrives'] = $valuenext->arrivaltime;
                        $flightarrayoutbound[$keynext]['destinationairport'] = $valuenext->arrivalaiport;
                        $flightarrayoutbound[$keynext]['flightno'] = $valuenext->oafn;
                    }

                }
                
            }  


            //saber price details
            if(isset($bookingdata->alldataofsaberoneflight)&& $bookingdata->alldataofsaberoneflight)
            {
                
                $totalprice = $bookingdata->alldataofsaberoneflight->AirItineraryPricingInfo->PTC_FareBreakdowns->PTC_FareBreakdown->PassengerFare->TotalFare->Amount;

                $priceperadulttotalfare = $bookingdata->alldataofsaberoneflight->AirItineraryPricingInfo->PTC_FareBreakdowns->PTC_FareBreakdown->PassengerFare->TotalFare->Amount;
                $priceperadulttax = $bookingdata->alldataofsaberoneflight->AirItineraryPricingInfo->PTC_FareBreakdowns->PTC_FareBreakdown->PassengerFare->Taxes->TotalTax->Amount;
            }
        }*/

        //user info to create user
        if(isset($noofpassengersandallflightdata['fn1']) 
            && $noofpassengersandallflightdata['fn1'] !=''
            && isset($customerinfo['email'])
            && $customerinfo['email'] != ''  
          ){

          $username = $noofpassengersandallflightdata['fn1']." ".$noofpassengersandallflightdata['mn1']." ".$noofpassengersandallflightdata['ln1'];
          $password = '123456';
          $email = $customerinfo['email'];

         
          /*echo "<pre>"; 
          print_r($noofpassengersandallflightdata); 
          print_r($creditcarddata); 
          print_r($customerinfo); 
          print_r($flightarray);
          print_r($flightarrayoutbound);
          print_r($totalprice);
          print_r($priceperadulttotalfare);
          print_r($priceperadulttax);
          die;*/

          //login to generate pnr
          global $base_url;
                
          $urltosendrequest = $base_url."/phpsaber/passengerdetails.php";
          $pnr = 'not available';
          $server_output = false;

          //book amadeus with amadeus booking system
          if($bookingdatatocheck->whoami!='amadeus')
          {
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL,$urltosendrequest);
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS,"btb=".$bodycontent);

            // in real life you should use something like:
            // curl_setopt($ch, CURLOPT_POSTFIELDS, 
            //          http_build_query(array('postvar1' => 'value1')));

            // receive server response ...
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

            $server_output = curl_exec ($ch);

            curl_close ($ch);
          }  
          
         
          // further processing ....
          if ($server_output) 
          {  
            $server_output = json_decode($server_output);
            if(isset($server_output->data))
            {
              $datatopass = base64_decode($server_output->data);
              $datatopass = json_decode($datatopass);
              if(isset($datatopass->TravelItineraryReadRS))
              {

                $TravelItineraryReadRS = $datatopass->TravelItineraryReadRS;
                $TravelItineraryReadRS = reset($TravelItineraryReadRS);
                
                $key = 'soap-env:Body';
                $TravelItineraryReadRS = $TravelItineraryReadRS->$key;
                $keycheck = 'stl:ApplicationResults';
                $keychecknext = 'stl:Success';
                if(isset($TravelItineraryReadRS->TravelItineraryReadRS->$keycheck->$keychecknext))
                {
                  $datatosave = $TravelItineraryReadRS->TravelItineraryReadRS->TravelItinerary;
                  $keypnr = '@attributes';
                  $pnr = $datatosave->ItineraryRef->$keypnr->ID;
                }
              }
            }
           } 
          

          
         
         

          
        }

        global $user;

        if ( $user->uid ) 
        {
          // Logged in user
          $useridofcurrentuser = $user->uid;
        }
        elseif(!$user->uid) 
        {
          // Not logged in
         
         
          $olduser = user_load_by_mail($email);
          
          if(!$olduser)
          {
            $oldusername = user_load_by_name($username);
            if($oldusername && $oldusername->mail != $email)
            {
              $username = $username.rand(10,100);
            }

              $new_user = array(
                'name' => $username,
                'pass' => $password, // note: do not md5 the password
                'mail' => $email,
                'status' => 1,
                'init' => $email,
                'roles' => array(
                  DRUPAL_AUTHENTICATED_RID => 'authenticated user',
                  4 => 'flightuser',
                ),
              );

              $uid = user_save('', $new_user);
              $useridofcurrentuser = $uid->uid;

              $to = strtolower($email);
              $from = strtolower("navinrai@flyoticket.com");
              $subject = "Thanks for booking flight with flyoticket.com";
              
              $msg = "Thanks for booking flight with Flyoticket. Your Username: ".$to." Password: ".$password." . Please login and check your booking status.     --Flyoticket Team";
              //echo $to = strtolower("navinkumar@geekexperthelp.com");
              //echo $from = strtolower("navinrai@travelpainters.com");
              //echo $subject = strtolower("I am working");
              $body = $msg;

              sendEmailSendGrid($to,$from,$subject,$body);
                      

          }elseif($olduser){

              $useridofcurrentuser = $olduser->uid;

              $to = strtolower($email);
              $from = strtolower("navinrai@flyoticket.com");
              $subject = "Thanks for booking flight with flyoticket.com";
              
              $msg = "Thanks for booking flight with Flyoticket. Your Username: ".$to." . Please login and check your booking status. If you you do not know your password please user forgotpassword link on Flyoticket.     --Flyoticket Team";
           
              $body = $msg;
              sendEmailSendGrid($to,$from,$subject,$body);
          }
          
        }


        if(isset($noofpassengersandallflightdata['fn1']) 
            && $noofpassengersandallflightdata['fn1'] !=''
            && isset($customerinfo['email'])
            && $customerinfo['email'] != ''  
          )
        {

          //total price of booking
          //$noofpassengersandallflightdata
          $totalfareofpassengers = isset($noofpassengersandallflightdata['totalfareofpassengers'])?$noofpassengersandallflightdata['totalfareofpassengers']:0;
          $totalnoofpassergers = isset($noofpassengersandallflightdata['totalnoofpassergers'])?$noofpassengersandallflightdata['totalnoofpassergers']:0;
          $totaladults = isset($noofpassengersandallflightdata['totaladults'])?$noofpassengersandallflightdata['totaladults']:0;
          $totalchildern = isset($noofpassengersandallflightdata['totalchildern'])?$noofpassengersandallflightdata['totalchildern']:0;
          $totalinfant = isset($noofpassengersandallflightdata['totalinfant'])?$noofpassengersandallflightdata['totalinfant']:0;

          $adultbtfare = isset($noofpassengersandallflightdata['adultbtfare'])?$noofpassengersandallflightdata['adultbtfare']:0;
          $adulttax = isset($noofpassengersandallflightdata['adulttax'])?$noofpassengersandallflightdata['adulttax']:0;
          $childbtfare = isset($noofpassengersandallflightdata['childbtfare'])?$noofpassengersandallflightdata['childbtfare']:0;
          $childtax = isset($noofpassengersandallflightdata['childtax'])?$noofpassengersandallflightdata['childtax']:0;
          $infantbtfare = isset($noofpassengersandallflightdata['infantbtfare'])?$noofpassengersandallflightdata['infantbtfare']:0;
          $infanttax = isset($noofpassengersandallflightdata['infanttax'])?$noofpassengersandallflightdata['infanttax']:0;



          $node = new stdClass();
          $node->title = $username."-".$email."-".date("Y-m-d h:i:s");
          $node->type = "flightbooking";
          node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
          $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
          $node->uid = $useridofcurrentuser;

          $node->body[$node->language][0]['value'] = $bodycontent;
          $node->body[$node->language][0]['summary'] = text_summary($bodycontent);
          $node->body[$node->language][0]['format'] = 'plain_text';

          //passenger one
          $node->field_first_name_one[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn1'])?$noofpassengersandallflightdata['fn1']:"none";
          $node->field_middel_name_one[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn1'])?$noofpassengersandallflightdata['mn1']:"none";
          $node->field_last_name_one[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln1'])?$noofpassengersandallflightdata['ln1']:"none";
          $node->field_date_of_birth_one[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob1'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob1'])):"none";
          $node->field_sex_one[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex1'])?$noofpassengersandallflightdata['sex1']:"none";

          //pessenger two
          $node->field_first_name_two[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn2'])?$noofpassengersandallflightdata['fn2']:"none";
          $node->field_middel_name_two[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn2'])?$noofpassengersandallflightdata['mn2']:"none";
          $node->field_last_name_two[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln2'])?$noofpassengersandallflightdata['ln2']:"none";
          $node->field_date_of_birth_two[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob2'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob2'])):"none";
          $node->field_sex_two[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex2'])?$noofpassengersandallflightdata['sex2']:"none";

          //pessenger three
          $node->field_first_name_three[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn3'])?$noofpassengersandallflightdata['fn3']:"none";
          $node->field_middel_name_three[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn3'])?$noofpassengersandallflightdata['mn3']:"none";
          $node->field_last_name_three[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln3'])?$noofpassengersandallflightdata['ln3']:"none";
          $node->field_date_of_birth_three[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob3'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob3'])):"none";
          $node->field_sex_three[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex3'])?$noofpassengersandallflightdata['sex3']:"none";

          //pessenger four field_middle_name_four[und][0][value]
          $node->field_first_name_four[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn4'])?$noofpassengersandallflightdata['fn4']:"none";
          $node->field_middle_name_four[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn4'])?$noofpassengersandallflightdata['mn4']:"none";
          $node->field_last_name_four[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln4'])?$noofpassengersandallflightdata['ln4']:"none";
          $node->field_date_of_birth_four[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob4'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob4'])):"none";
          $node->field_sex_four[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex4'])?$noofpassengersandallflightdata['sex4']:"none";

          //pessenger five
          $node->field_first_name_five[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn5'])?$noofpassengersandallflightdata['fn5']:"none";
          $node->field_middel_name_five[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn5'])?$noofpassengersandallflightdata['mn5']:"none";
          $node->field_last_name_five[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln5'])?$noofpassengersandallflightdata['ln5']:"none";
          $node->field_date_of_birth_five[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob5'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob5'])):"none";
          $node->field_sex_five[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex5'])?$noofpassengersandallflightdata['sex5']:"none";

          /* ------------------------------------------------ */
          //pessenger six
          $node->field_first_name_six[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn6'])?$noofpassengersandallflightdata['fn6']:"none";
          $node->field_middel_name_six[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn6'])?$noofpassengersandallflightdata['mn6']:"none";
          $node->field_last_name_six[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln6'])?$noofpassengersandallflightdata['ln6']:"none";
          $node->field_date_of_birth_six[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob6'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob6'])):"none";
          $node->field_sex_six[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex6'])?$noofpassengersandallflightdata['sex6']:"none";

          //pessenger seven
          $node->field_first_name_seven[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn7'])?$noofpassengersandallflightdata['fn7']:"none";
          $node->field_middel_name_seven[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn7'])?$noofpassengersandallflightdata['mn7']:"none";
          $node->field_last_name_seven[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln7'])?$noofpassengersandallflightdata['ln7']:"none";
          $node->field_date_of_birth_seven[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob7'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob7'])):"none";
          $node->field_sex_seven[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex7'])?$noofpassengersandallflightdata['sex7']:"none";

          //pessenger eight
          $node->field_first_name_eight[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn8'])?$noofpassengersandallflightdata['fn8']:"none";
          $node->field_middel_name_eight[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn8'])?$noofpassengersandallflightdata['mn8']:"none";
          $node->field_last_name_eight[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln8'])?$noofpassengersandallflightdata['ln8']:"none";
          $node->field_date_of_birth_eight[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob8'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob8'])):"none";
          $node->field_sex_eight[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex8'])?$noofpassengersandallflightdata['sex8']:"none";

          //pessenger nine
          $node->field_first_name_nine[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['fn9'])?$noofpassengersandallflightdata['fn9']:"none";
          $node->field_middel_name_nine[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['mn9'])?$noofpassengersandallflightdata['mn9']:"none";
          $node->field_last_name_nine[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['ln9'])?$noofpassengersandallflightdata['ln9']:"none";
          $node->field_date_of_birth_nine[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['dob9'])?date('Y-m-d',strtotime($noofpassengersandallflightdata['dob9'])):"none";
          $node->field_sex_nine[LANGUAGE_NONE][0]['value'] = isset($noofpassengersandallflightdata['sex9'])?$noofpassengersandallflightdata['sex9']:"none";


          /* ------------------------------------------------ */

          //allflightdata field_allflightdata[und][0][value]
          $node->field_allflightdata[LANGUAGE_NONE][0]['value'] = $allflightdatatosave;

          //type of card field_type_of_card[und][0][value]
          $node->field_type_of_card[LANGUAGE_NONE][0]['value'] = $creditcarddata['typepfcard'];  

          //credit card no. field_credit_card_no[und][0][value]
          $node->field_credit_card_no[LANGUAGE_NONE][0]['value'] = $creditcarddata['cc'];  

          //ccv no field_ccv[und][0][value]
          $node->field_ccv[LANGUAGE_NONE][0]['value'] = $creditcarddata['ccv'];  

          //ccn field_ccn[und][0][value]
          $node->field_ccn[LANGUAGE_NONE][0]['value'] = $creditcarddata['ccn']; 

          //expiry ccvth field_ccexpiry[und][0][value]
          $node->field_ccexpiry[LANGUAGE_NONE][0]['value'] = $creditcarddata['ccvth']; 

          //field_country[und][0][value] country
          $node->field_country[LANGUAGE_NONE][0]['value'] = $customerinfo['country'];

          //street field_street[und][0][value]
          $node->field_street[LANGUAGE_NONE][0]['value'] = $customerinfo['street'];

          //field_city[und][0][value] city
          $node->field_city[LANGUAGE_NONE][0]['value'] = $customerinfo['city'];
          
          //field_state[und][0][value] state
          $node->field_state[LANGUAGE_NONE][0]['value'] = $customerinfo['state'];

          //field_zipcode[und][0][value] zipcode
          $node->field_zipcode[LANGUAGE_NONE][0]['value'] = $customerinfo['zipcode'];

          //field_business_phone[und][0][value] bp
          $node->field_business_phone[LANGUAGE_NONE][0]['value'] = $customerinfo['bp'];

          //field_mobile_phone[und][0][value] mp
          $node->field_mobile_phone[LANGUAGE_NONE][0]['value'] = $customerinfo['mp'];

          //field_email[und][0][value] email
          $node->field_email[LANGUAGE_NONE][0]['value'] = $customerinfo['email'];


          //field_total_price[und][0][value] $totalprice
          $node->field_total_price[LANGUAGE_NONE][0]['value'] = $adultbtfare+$adulttax;

          //field_total_price[und][0][value] $totalprice
          $node->field_total_price[LANGUAGE_NONE][0]['value'] = $adultbtfare+$adulttax;

          //field_price_per_person[und][0][value]  $priceperadulttotalfare
          $node->field_price_per_person[LANGUAGE_NONE][0]['value'] = $adultbtfare; 

          /* ------------------- */
          //field_price_per_person[und][0][value]  $priceperadulttotalfare
          $node->field_totalnoofpassergers[LANGUAGE_NONE][0]['value'] = $totalnoofpassergers;

          $node->field_totaladults[LANGUAGE_NONE][0]['value'] = $totaladults;
          $node->field_totalchildren[LANGUAGE_NONE][0]['value'] = $totalchildern;
          $node->field_totalinfant[LANGUAGE_NONE][0]['value'] = $totalinfant;
          $node->field_adultbtfare[LANGUAGE_NONE][0]['value'] = $adultbtfare;
          $node->field_adulttax[LANGUAGE_NONE][0]['value'] = $adulttax;
          $node->field_childbtfare[LANGUAGE_NONE][0]['value'] = $childbtfare;
          $node->field_childtax[LANGUAGE_NONE][0]['value'] = $childtax;
          $node->field_infantbtfare[LANGUAGE_NONE][0]['value'] = $infantbtfare; 
          $node->field_infanttax[LANGUAGE_NONE][0]['value'] = $infanttax; 


          /* ------------------- */
          
          //field_tax[und][0][value]  $priceperadulttax
          $node->field_tax[LANGUAGE_NONE][0]['value'] = $adulttax;         

          $flightdata = json_encode(array('flightarray'=>$flightarray,'flightarrayoutbound'=>$flightarrayoutbound));
          
          //field_flightdata[und][0][value] 
          $node->field_flightdata[LANGUAGE_NONE][0]['value'] = $flightdata;

          //noofpassenger
          $node->field_noofpassenger[LANGUAGE_NONE][0]['value'] = $totalnoofpassergers;

          //totalpriceofbooking
          $node->field_totalpriceofbooking[LANGUAGE_NONE][0]['value'] = $totalfareofpassengers;

          //pnr
          $node->field_pnr[LANGUAGE_NONE][0]['value'] = $pnr;
          

          $i=1;
          $passengerinfo = array();
          for ($i=1; $i < 51 ; $i++) { 
              $fnkey = 'fn'.$i;
              $mnkey = 'mn'.$i;
              $lnkey = 'ln'.$i;
              $dobkey = 'dob'.$i;
              $sexkey = 'sex'.$i;

              $firstname = isset($noofpassengersandallflightdata[$fnkey])?$noofpassengersandallflightdata[$fnkey]:"none";
              $middlename = isset($noofpassengersandallflightdata[$mnkey])?$noofpassengersandallflightdata[$mnkey]:"none";
              $lastname = isset($noofpassengersandallflightdata[$lnkey])?$noofpassengersandallflightdata[$lnkey]:"none";
              $dob = isset($noofpassengersandallflightdata[$dobkey])?$noofpassengersandallflightdata[$dobkey]:"none";
              $sex = isset($noofpassengersandallflightdata[$sexkey])?$noofpassengersandallflightdata[$sexkey]:"none";

              $passengerinfo[$i] = array($firstname,$middlename,$lastname,$dob,$sex);
          } 

          //field_passengers[und][0][value]
          $node->field_passengers[LANGUAGE_NONE][0]['value'] = json_encode($passengerinfo);

          $node->status = 1; //(1 or 0): published or not
          $node->promote = 0; //(1 or 0): promoted to front page
          $node->comment = 1; // 0 = comments disabled, 1 = read only, 2 = read/write

          $node = node_submit($node); // Prepare node for saving
          $nodeinfo = node_save($node);
          global $base_url;
          $burl = $base_url."/bookingsuccess";
          drupal_goto($burl, array('query'=>array('bid'=>$node->nid)));
          return true;
        }
    
       

    

  }
  return 'success';
}

/*
function custmail_mail_alter(&$message) {
  
  //user registration email from travelpainters register as flight user
  if($message['id'] == "user_registrationpassword_register" && $message['key'] == 'register')
  {
    $to = strtolower($message['to']);
    $from = strtolower("navinrai@travelpainters.com");
    $subject = $message['subject'];
    $body = reset($message['body']);
    $string = $body;
    $regex = '/\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|$!:,.;]*[A-Z0-9+&@#\/%=~_|$]/i';
    preg_match_all($regex, $string, $matches);
    $urls = $matches[0];
    $urltosend = reset($urls);
    $msg = "Thank you for registering at Travelpainters. You may now log in and verify your account by clicking this link or copying and pasting it to your browser: ".$urltosend. " This link can only be used once to login and change your password. "." Your Username: ".$to." Password: Your Password . Please also check your junk or spam folder some times custom setting of inbox redirect good emails to spam or junk folder.     --Travelpainters Team";
    //echo $to = strtolower("navinkumar@geekexperthelp.com");
    //echo $from = strtolower("navinrai@travelpainters.com");
    //echo $subject = strtolower("I am working");
    $body = $msg;

    sendEmailSendGrid($to,$from,$subject,$body);
    $_SESSION['userregisteredmessage'] = "Thank you form Travelpainters. Please check Your email and use the link to verify.";
    //sendEmailSendGrid($to,$from,$subject,$body);
  }

   //echo "<pre>"; print_r($message); die;
     sleep(2);  
    return $message;
}
*/



function shownodes_admin_settings() {

  $types = node_type_get_types();
  foreach($types as $node_type) {
    $nodetypes[$node_type->type] = $node_type->name;
  }

  $form['shownodes_nodes_toshow'] = array(
  '#type' => 'checkboxes',
  '#title' => t('Select the nodes to show'),
  '#options' => $nodetypes,
  '#default_value' => variable_get('shownodes_nodes_toshow', array('')),
  '#description' => t('All the node types selected below will be shown'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 */
function shownodes_block_info() {
  $blocks = array();

  $blocks['shownodeblock'] = array(
    'info' => t('A block to show selected nodes'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function shownodes_block_view($block_name = '') {
  if ($block_name == 'shownodeblock') {

    //Get the selected node types and create a list of them
    $show_nodes_list = array();
    $show_nodes_array = variable_get('shownodes_nodes_toshow', array(''));
    foreach ($show_nodes_array as $key => $value) {
      if($value) {
          array_push($show_nodes_list,$value);
      }
    }

    //Based on the node types create a query and then load the node types
    $query = new EntityFieldQuery();
    $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $show_nodes_list)
    ->propertyCondition('status', 1)
    ->propertyOrderBy('created', 'DESC');

    $result = $query->execute();
    $nodes = array();
    if (isset($result['node'])) {
      $nids = array_keys($result['node']);
      $nodes = entity_load('node', $nids);
    }

    //Loop through the loded nodes to create a list
    //Which we will pass to the theme
    $list = array();
    $i = 0;
    foreach ($nodes as $node) {
      $options = array('absolute' => TRUE);
      $url = url('node/' . $node->nid, $options);
      $list[$i] = '<a href='.$url.'>'.$node->title.'</a>';
      $i++;
    }

    //Return the content of the block
    $theme_args = array('items' => $list, 'type' => 'ol');
    $content = theme('item_list', $theme_args);

    $block = array(
      'subject' => t('Show Nodes Block'),
      'content' => $content,
    );
    return $block;
  }
}
