filter:
    excluded_paths:
          - tests/*
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 1
build: 
    environment:
        php: 5.6
