<?php

function custmail_mail_alter(&$message) {
	
	//user registration email from travelpainters register as flight user
	if($message['id'] == "user_registrationpassword_register" && $message['key'] == 'register')
	{
		$to = strtolower($message['to']);
		$from = strtolower("navinrai@travelpainters.com");
		$subject = $message['subject'];
		$body = reset($message['body']);
		$string = $body;
		$regex = '/\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|$!:,.;]*[A-Z0-9+&@#\/%=~_|$]/i';
		preg_match_all($regex, $string, $matches);
		$urls = $matches[0];
		$urltosend = reset($urls);
		$msg = "Thank you for registering at Travelpainters. You may now log in and verify your account by clicking this link or copying and pasting it to your browser: ".$urltosend. " This link can only be used once to login and change your password. "." Your Username: ".$to." Password: Your Password . Please also check your junk or spam folder some times custom setting of inbox redirect good emails to spam or junk folder.     --Travelpainters Team";
		
		$body = $msg;

		sendEmailSendGrid($to,$from,$subject,$body);
		$_SESSION['userregisteredmessage'] = "Thank you form Travelpainters. Please check Your email and use the link to verify.";
	
	}

	 //echo "<pre>"; print_r($message); die;
   	 sleep(2);	
    return $message;
}


function sendEmailSendGrid($to,$from,$subject,$body){
	$curl = curl_init();
	
	curl_setopt_array($curl, array(
	  CURLOPT_URL => "https://api.sendgrid.com/v3/mail/send",
	  CURLOPT_RETURNTRANSFER => true,
	  CURLOPT_ENCODING => "",
	  CURLOPT_MAXREDIRS => 10,
	  CURLOPT_SSL_VERIFYPEER => false,
	  CURLOPT_TIMEOUT => 30,
	  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
	  CURLOPT_CUSTOMREQUEST => "POST",
	  CURLOPT_POSTFIELDS => '{"personalizations": [{"to": [{"email": "'.$to.'"}]}],"from": {"email": "'.$from.'"},"subject": "'.$subject.'","content": [{"type": "text/html", "value": "'.$body.'"}]}',
	  CURLOPT_HTTPHEADER => array(
	    "authorization: Bearer ",
	    "cache-control: no-cache",
	    "content-type: application/json"
	  ),
	));
	$response = curl_exec($curl);
	sleep(3);
	$err = curl_error($curl);

	curl_close($curl);
	//header('Location: thanks.html');
	if ($err) {
	  echo "Mail Send Error #:" . $err; die;
	} else {
	  return true;
	}

	return false;
}


function custmail_menu() {
    $items = array();

    $items['custmail/hello_world'] = array(
        'title' => 'Hello World Test',
        'page callback' => 'say_hello_world',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );

    return $items;
}

function say_hello_world() {
	$to = strtolower("navinkumar@geekexperthelp.com");
	$from = strtolower("navinrai@travelpainters.com");
	$subject = strtolower("I am working");
	$body = strtolower("hello friends i am back !!");

	sendEmailSendGrid($to,$from,$subject,$body);
    $vars = array();
    $vars['type']="ul";
    $vars['title'] = "";
    $vars['attributes']=array("");
    $vars['items'][0]="This is a simple proof of concept module";

    return theme_item_list($vars);
}

?>
